name: GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
#    - name: Build
#      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  docker:
    
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/cryptografie:latest
        
  azure:
  
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Login to Azure
      uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    - name: Setup Dotnet 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
#    - name: Restore dependencies
#      run: 
#        dotnet restore
    - name: Build
      run:
        dotnet build --configuration Release
    - name: Publish
      run:
        dotnet publish -c Release -o './myapp'
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: Cryptografie
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: './myapp'
